module.exports.COUNTRY_NAME = {

    'Afghanistan': { male: 63, female: 33 },
    'Albania': { male: 77, female: 33 },
    'Algeria': { male: 76, female: 33 },
    'Angola': { male: 58, female: 33 },
    'Antigua & Deps': { male: 76, female: 33 },
    'Argentina': { male: 73, female: 33 },
    'Armenia': { male: 71, female: 33 },
    'Aruba': { male: 74, female: 33 },
    'Australia': { male: 33, female: 33 },
    'Austria': { male: 33, female: 33 },
    'Azerbaijan': { male: 33, female: 33 },
    'Bahamas': { male: 33, female: 33 },
    'Bahrain': { male: 33, female: 33 },
    'Bangladesh': { male: 33, female: 33 },
    'Barbados': { male: 33, female: 33 },
    'Belarus': { male: 33, female: 33 },
    'Belgium': { male: 33, female: 33 },
    'Belize': { male: 33, female: 33 },
    'Benin': { male: 33, female: 33 },
    'Bhutan': { male: 33, female: 33 },
    'Bolivia': { male: 33, female: 33 },
    'Bosnia Herzegovina': { male: 33, female: 33 },
    'Botswana': { male: 33, female: 33 },
    'Brazil': { male: 33, female: 33 },
    'Brunei': { male: 33, female: 33 },
    'Bulgaria': { male: 33, female: 33 },
    'Burkina': { male: 33, female: 33 },
    'Burundi': { male: 33, female: 33 },
    'Cambodia': { male: 33, female: 33 },
    'Cameroon': { male: 33, female: 33 },
    'Canada': { male: 33, female: 33 },
    'Cape Verde': { male: 33, female: 33 },
    'Central African Rep': { male: 33, female: 33 },
    'Chad': { male: 33, female: 33 },
    'Chile': { male: 33, female: 33 },
    'China': { male: 33, female: 33 },
    'Colombia': { male: 33, female: 33 },
    'Comoros': { male: 33, female: 33 },
    'Congo': { male: 33, female: 33 },
    'Costa Rica': { male: 33, female: 33 },
    'Croatia': { male: 33, female: 33 },
    'Cuba': { male: 33, female: 33 },
    'Cyprus': { male: 33, female: 33 },
    'Czech Republic': { male: 33, female: 33 },
    'Denmark': { male: 33, female: 33 },
    'Djibouti': { male: 33, female: 33 },
    'Dominica': { male: 33, female: 33 },
    'Dominican Republic': { male: 33, female: 33 },
    'East Timor': { male: 33, female: 33 },
    'Ecuador': { male: 33, female: 33 },
    'Egypt': { male: 33, female: 33 },
    'El Salvador': { male: 33, female: 33 },
    'Equatorial Guinea': { male: 33, female: 33 },
    'Eritrea': { male: 33, female: 33 },
    'Estonia': { male: 33, female: 33 },
    'Ethiopia': { male: 33, female: 33 },
    'Fiji': { male: 33, female: 33 },
    'Finland': { male: 33, female: 33 },
    'France': { male: 33, female: 33 },
    'Gabon': { male: 33, female: 33 },
    'Gambia': { male: 33, female: 33 },
    'Georgia': { male: 33, female: 33 },
    'Germany': { male: 33, female: 33 },
    'Ghana': { male: 33, female: 33 },
    'Greece': { male: 33, female: 33 },
    'Grenada': { male: 33, female: 33 },
    'Guatemala': { male: 33, female: 33 },
    'Guinea': { male: 33, female: 33 },
    'Guinea-Bissau': { male: 33, female: 33 },
    'Guyana': { male: 33, female: 33 },
    'Haiti': { male: 33, female: 33 },
    'Honduras': { male: 33, female: 33 },
    'Hungary': { male: 33, female: 33 },
    'Iceland': { male: 33, female: 33 },
    'India': { male: 33, female: 33 },
    'Indonesia': { male: 33, female: 33 },
    'Iran': { male: 33, female: 33 },
    'Iraq': { male: 33, female: 33 },
    'Ireland': { male: 33, female: 33 },
    'Israel': { male: 33, female: 33 },
    'Italy': { male: 33, female: 33 },
    'Ivory Coast': { male: 33, female: 33 },
    'Jamaica': { male: 33, female: 33 },
    'Japan': { male: 33, female: 33 },
    'Jordan': { male: 33, female: 33 },
    'Kazakhstan': { male: 33, female: 33 },
    'Kenya': { male: 33, female: 33 },
    'Kiribati': { male: 33, female: 33 },
    'Korea North': { male: 33, female: 33 },
    'Korea South': { male: 33, female: 33 },
    'Kosovo': { male: 33, female: 33 },
    'Kuwait': { male: 33, female: 33 },
    'Kyrgyzstan': { male: 33, female: 33 },
    'Laos': { male: 33, female: 33 },
    'Latvia': { male: 33, female: 33 },
    'Lebanon': { male: 33, female: 33 },
    'Lesotho': { male: 33, female: 33 },
    'Liberia': { male: 33, female: 33 },
    'Libya': { male: 33, female: 33 },
    'Liechtenstein': { male: 33, female: 33 },
    'Lithuania': { male: 33, female: 33 },
    'Luxembourg': { male: 33, female: 33 },
    'Macedonia': { male: 33, female: 33 },
    'Madagascar': { male: 33, female: 33 },
    'Malawi': { male: 33, female: 33 },
    'Malaysia': { male: 33, female: 33 },
    'Maldives': { male: 33, female: 33 },
    'Mali': { male: 33, female: 33 },
    'Malta': { male: 33, female: 33 },
    'Marshall Islands': { male: 33, female: 33 },
    'Mauritania': { male: 33, female: 33 },
    'Mauritius': { male: 33, female: 33 },
    'Mexico': { male: 33, female: 33 },
    'Micronesia': { male: 33, female: 33 },
    'Moldova': { male: 33, female: 33 },
    'Monaco': { male: 33, female: 33 },
    'Mongolia': { male: 33, female: 33 },
    'Montenegro': { male: 33, female: 33 },
    'Morocco': { male: 33, female: 33 },
    'Mozambique': { male: 33, female: 33 },
    'Myanmar': { male: 33, female: 33 },
    'Namibia': { male: 33, female: 33 },
    'Nauru': { male: 33, female: 33 },
    'Nepal': { male: 33, female: 33 },
    'Netherlands': { male: 33, female: 33 },
    'New Zealand': { male: 33, female: 33 },
    'Nicaragua': { male: 33, female: 33 },
    'Niger': { male: 33, female: 33 },
    'Nigeria': { male: 33, female: 33 },
    'Norway': { male: 33, female: 33 },
    'Oman': { male: 33, female: 33 },
    'Pakistan': { male: 33, female: 33 },
    'Palau': { male: 33, female: 33 },
    'Panama': { male: 33, female: 33 },
    'Papua New Guinea': { male: 33, female: 33 },
    'Paraguay': { male: 33, female: 33 },
    'Peru': { male: 33, female: 33 },
    'Philippines': { male: 33, female: 33 },
    'Poland': { male: 33, female: 33 },
    'Portugal': { male: 33, female: 33 },
    'Qatar': { male: 33, female: 33 },
    'Romania': { male: 33, female: 33 },
    'Russian Federation': { male: 33, female: 33 },
    'Rwanda': { male: 33, female: 33 },
    'St Kitts & Nevis': { male: 33, female: 33 },
    'St Lucia': { male: 33, female: 33 },
    'Saint Vincent & the Grenadin': { male: 33, female: 33 },
    'Samoa': { male: 33, female: 33 },
    'San Marino': { male: 33, female: 33 },
    'Sao Tome & Principe': { male: 33, female: 33 },
    'Saudi Arabia': { male: 33, female: 33 },
    'Senegal': { male: 33, female: 33 },
    'Serbia': { male: 33, female: 33 },
    'Seychelles': { male: 33, female: 33 },
    'Sierra Leone': { male: 33, female: 33 },
    'Singapore': { male: 33, female: 33 },
    'Slovakia': { male: 33, female: 33 },
    'Solomon Islands': { male: 33, female: 33 },
    'Somalia': { male: 33, female: 33 },
    'South Africa': { male: 33, female: 33 },
    'South Sudan': { male: 33, female: 33 },
    'Spain': { male: 33, female: 33 },
    'Sri Lanka': { male: 33, female: 33 },
    'Sudan': { male: 33, female: 33 },
    'Suriname': { male: 33, female: 33 },
    'Swaziland': { male: 33, female: 33 },
    'Sweden': { male: 33, female: 33 },
    'Switzerland': { male: 33, female: 33 },
    'Syria': { male: 33, female: 33 },
    'Taiwan': { male: 33, female: 33 },
    'Tajikistan': { male: 33, female: 33 },
    'Tanzania': { male: 33, female: 33 },
    'Thailand': { male: 33, female: 33 },
    'Togo': { male: 33, female: 33 },
    'Tonga': { male: 33, female: 33 },
    'Trinidad & Tobago': { male: 33, female: 33 },
    'Tunisia': { male: 33, female: 33 },
    'Turkey': { male: 33, female: 33 },
    'Turkmenistan': { male: 33, female: 33 },
    'Tuvalu': { male: 33, female: 33 },
    'Uganda': { male: 33, female: 33 },
    'Ukraine': { male: 33, female: 33 },
    'United Arab Emirates': { male: 33, female: 33 },
    'United Kingdom': { male: 33, female: 33 },
    'United States': { male: 33, female: 33 },
    'Uruguay': { male: 33, female: 33 },
    'Uzbekistan': { male: 33, female: 33 },
    'Vanuatu': { male: 33, female: 33 },
    'Vatican City': { male: 33, female: 33 },
    'Venezuela': { male: 33, female: 33 },
    'Vietnam': { male: 33, female: 33 },
    'Yemen': { male: 33, female: 33 },
    'Zambia': { male: 33, female: 33 },
    'Zimbabwe': { male: 33, female: 33 },
}